name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
          fetch-depth: 0
      - name: Deploy to Staging
        id: staging
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_STAGING }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "src/DevOpsAssistant/DevOpsAssistant"
          output_location: "wwwroot"
      - name: Export URL
        run: echo "STAGING_URL=${{ steps.staging.outputs.static_web_app_url }}" >> $GITHUB_ENV

  smoke_tests:
    runs-on: ubuntu-latest
    needs: deploy_staging
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore
        run: dotnet restore src/DevOpsAssistant/DevOpsAssistant.sln
      - name: Run smoke tests
        run: dotnet test src/DevOpsAssistant/DevOpsAssistant.SmokeTests/DevOpsAssistant.SmokeTests.csproj --no-restore --verbosity normal
        env:
          STAGING_URL: ${{ env.STAGING_URL }}

  deploy_production:
    runs-on: ubuntu-latest
    needs: smoke_tests
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
          fetch-depth: 0
      - name: Deploy to Production
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BRAVE_ROCK_022B8FE03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "src/DevOpsAssistant/DevOpsAssistant"
          output_location: "wwwroot"
