name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore
        run: dotnet restore src/DevOpsAssistant/DevOpsAssistant.sln
      - name: Start site
        run: |
          dotnet run --project src/DevOpsAssistant/DevOpsAssistant/DevOpsAssistant.csproj &
          echo $! > site.pid
          sleep 10
      - name: Test with coverage
        run: dotnet test src/DevOpsAssistant/DevOpsAssistant.sln --no-restore --verbosity normal --collect:"XPlat Code Coverage"
        env:
          STAGING_URL: http://localhost:5000
      - name: Stop site
        run: kill $(cat site.pid)
      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool
      - name: Generate coverage report
        run: |
          reportgenerator -reports:"**/coverage.cobertura.xml" -targetdir:"coverage-report" -reporttypes:Html
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage-report
